/**
 * @file AnnotationThread.tsx
 *
 * Annotation thread UI components for the wiki inline annotation system.
 *
 * ## Component hierarchy
 *
 *   AnnotationSidebar
 *   └── AnnotationThreadCard      — renders one thread with replies
 *         └── AnnotationReplyForm — inline reply input
 *
 *   AgentAnnotationThread         — renders a wiki_annotation entity thread
 *         └── AgentMessageBadge  — "Agent" label on every agent-authored message
 *
 * ## Usage
 *
 * Mount `AnnotationSidebar` alongside `WikiRender`. Pass the customerId and
 * versionId so it can fetch and post threads.
 *
 * Mount `AgentAnnotationThread` where annotation correction threads
 * (from the Anthropic API annotation flow) are shown. Each agent message will
 * display an "Agent" badge so users can never be confused about authorship.
 *
 * @see https://github.com/superfield-ai/superfield-kb-demo/issues/63
 * @see https://github.com/superfield-ai/superfield-kb-demo/issues/68
 */

import React, { useCallback, useEffect, useRef, useState } from 'react';

// ---------------------------------------------------------------------------
// Agent annotation message types (issue #68)
// Mirror the server-side AnnotationMessage / AuthorKind shapes.
// ---------------------------------------------------------------------------

/**
 * Author kind for an annotation message.
 * 'human' — written by the Records Manager.
 * 'agent' — generated by the Anthropic API annotation agent.
 */
export type AuthorKind = 'human' | 'agent';

/**
 * A single message in a wiki_annotation entity thread.
 * Mirrors apps/server/src/api/annotations.ts AnnotationMessage.
 */
export interface AgentAnnotationMessage {
  role: 'rm' | 'agent';
  author_kind: AuthorKind;
  content: string;
  created_at: string;
}

// ---------------------------------------------------------------------------
// AgentMessageBadge — visible "Agent" label on every agent-authored message
// ---------------------------------------------------------------------------

/**
 * Renders a small pill badge that labels a message as agent-authored.
 *
 * Always rendered for messages with author_kind='agent'. The badge text
 * "Agent" is visible at all times so users can never be confused about
 * whether they are talking to a human or an agent.
 */
export function AgentMessageBadge(): React.ReactElement {
  return (
    <span
      data-testid="agent-message-badge"
      className="inline-flex items-center gap-1 text-[10px] font-semibold uppercase tracking-wide text-violet-700 bg-violet-50 border border-violet-200 px-1.5 py-0.5 rounded"
    >
      Agent
    </span>
  );
}

// ---------------------------------------------------------------------------
// AgentAnnotationThread — renders a wiki_annotation entity thread with labels
// ---------------------------------------------------------------------------

/**
 * Renders the full message thread of a wiki_annotation entity.
 *
 * Every message with `author_kind='agent'` displays an `AgentMessageBadge`
 * so the user always knows which messages were generated by an AI agent.
 *
 * This component is the canonical UI surface for the agent visibility
 * requirement described in issue #68.
 */
export function AgentAnnotationThread({
  messages,
}: {
  messages: AgentAnnotationMessage[];
}): React.ReactElement {
  return (
    <ul data-testid="agent-annotation-thread" className="flex flex-col gap-2">
      {messages.map((msg, idx) => (
        <li
          key={idx}
          data-testid={
            msg.author_kind === 'agent' ? 'agent-annotation-message' : 'human-annotation-message'
          }
          className={`rounded-md border px-3 py-2 ${
            msg.author_kind === 'agent'
              ? 'border-violet-200 bg-violet-50'
              : 'border-zinc-200 bg-white'
          }`}
        >
          <div className="flex items-center gap-2 mb-1">
            <span className="text-[11px] font-medium text-zinc-500">
              {msg.author_kind === 'agent' ? 'Agent' : 'You'}
            </span>
            {msg.author_kind === 'agent' && <AgentMessageBadge />}
          </div>
          <p className="text-xs text-zinc-800">{msg.content}</p>
          <p className="mt-0.5 text-[10px] text-zinc-400">{msg.created_at}</p>
        </li>
      ))}
    </ul>
  );
}

// ---------------------------------------------------------------------------
// Types (mirror the server-side shapes)
// ---------------------------------------------------------------------------

export interface AnnotationReply {
  id: string;
  thread_id: string;
  body: string;
  created_by: string;
  created_at: string;
}

export interface AnnotationThread {
  id: string;
  wiki_version_id: string;
  anchor_text: string;
  start_offset: number;
  end_offset: number;
  body: string;
  created_by: string;
  resolved: boolean;
  resolved_by: string | null;
  resolved_at: string | null;
  created_at: string;
  updated_at: string;
  replies: AnnotationReply[];
}

// ---------------------------------------------------------------------------
// Anchor re-computation — fuzzy re-anchoring after small edits
// ---------------------------------------------------------------------------

/**
 * Re-anchors a thread against the current version content.
 *
 * Strategy (three-tier):
 *   1. Exact match at the stored offset — content unchanged.
 *   2. Substring search — finds the anchor text anywhere in the content.
 *   3. Unavailable — content changed too much; returns null.
 *
 * Returns the resolved (start, end) offsets or null when unavailable.
 */
export function resolveAnchor(
  content: string,
  thread: Pick<AnnotationThread, 'anchor_text' | 'start_offset' | 'end_offset'>,
): { start: number; end: number } | null {
  const { anchor_text, start_offset, end_offset } = thread;
  const expected = end_offset - start_offset;

  // 1. Exact offset match.
  if (content.slice(start_offset, end_offset) === anchor_text) {
    return { start: start_offset, end: end_offset };
  }

  // 2. Search for the anchor text anywhere in the content (smallest offset wins).
  const found = content.indexOf(anchor_text);
  if (found !== -1) {
    return { start: found, end: found + expected };
  }

  // 3. Unavailable.
  return null;
}

// ---------------------------------------------------------------------------
// AnnotationThreadCard
// ---------------------------------------------------------------------------

/**
 * Renders a single annotation thread with its replies and a reply input.
 */
export function AnnotationThreadCard({
  thread,
  customerId,
  versionId,
  active,
  onClick,
  onResolved,
  onReplyPosted,
}: {
  thread: AnnotationThread;
  customerId: string;
  versionId: string;
  active: boolean;
  onClick: () => void;
  onResolved: (threadId: string, resolved: boolean) => void;
  onReplyPosted: (threadId: string, reply: AnnotationReply) => void;
}): React.ReactElement {
  const [replyBody, setReplyBody] = useState('');
  const [posting, setPosting] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const replyInputRef = useRef<HTMLTextAreaElement>(null);

  const handleReply = useCallback(
    async (e: React.FormEvent) => {
      e.preventDefault();
      if (!replyBody.trim()) return;
      setPosting(true);
      setError(null);
      try {
        const res = await fetch(
          `/api/wiki/pages/${encodeURIComponent(customerId)}/versions/${encodeURIComponent(versionId)}/annotations/${encodeURIComponent(thread.id)}/replies`,
          {
            method: 'POST',
            credentials: 'include',
            headers: { 'Content-Type': 'application/json' },
            body: JSON.stringify({ body: replyBody.trim() }),
          },
        );
        if (!res.ok) {
          const body = await res.json().catch(() => ({}));
          throw new Error((body as { error?: string }).error ?? `HTTP ${res.status}`);
        }
        const reply = (await res.json()) as AnnotationReply;
        onReplyPosted(thread.id, reply);
        setReplyBody('');
      } catch (err) {
        setError(err instanceof Error ? err.message : 'Failed to post reply');
      } finally {
        setPosting(false);
      }
    },
    [replyBody, customerId, versionId, thread.id, onReplyPosted],
  );

  const handleResolve = useCallback(async () => {
    const newResolved = !thread.resolved;
    try {
      const res = await fetch(
        `/api/wiki/pages/${encodeURIComponent(customerId)}/versions/${encodeURIComponent(versionId)}/annotations/${encodeURIComponent(thread.id)}`,
        {
          method: 'PATCH',
          credentials: 'include',
          headers: { 'Content-Type': 'application/json' },
          body: JSON.stringify({ resolved: newResolved }),
        },
      );
      if (!res.ok) throw new Error(`HTTP ${res.status}`);
      onResolved(thread.id, newResolved);
    } catch (err) {
      console.error('[AnnotationThreadCard] resolve failed:', err);
    }
  }, [customerId, versionId, thread.id, thread.resolved, onResolved]);

  return (
    <div
      data-testid="annotation-thread-card"
      data-thread-id={thread.id}
      onClick={onClick}
      className={`rounded-lg border transition-all cursor-pointer ${
        active
          ? 'border-indigo-400 bg-indigo-50'
          : thread.resolved
            ? 'border-zinc-200 bg-zinc-50 opacity-60'
            : 'border-zinc-200 bg-white hover:border-zinc-300'
      }`}
    >
      {/* Thread header */}
      <div className="px-3 pt-2.5 pb-1">
        <div className="flex items-start justify-between gap-2">
          <blockquote
            data-testid="annotation-anchor-text"
            className="text-[11px] text-zinc-500 italic border-l-2 border-indigo-300 pl-2 truncate max-w-[160px]"
          >
            {thread.anchor_text}
          </blockquote>
          {thread.resolved && (
            <span className="shrink-0 text-[10px] font-semibold uppercase tracking-wide text-emerald-600 bg-emerald-50 border border-emerald-200 px-1.5 py-0.5 rounded">
              resolved
            </span>
          )}
        </div>
        <p className="mt-1.5 text-xs text-zinc-800">{thread.body}</p>
        <p className="mt-1 text-[11px] text-zinc-400">{thread.created_by}</p>
      </div>

      {/* Replies */}
      {thread.replies.length > 0 && (
        <ul className="border-t border-zinc-100 mt-1">
          {thread.replies.map((reply) => (
            <li
              key={reply.id}
              data-testid="annotation-reply"
              className="px-3 py-2 border-b border-zinc-100 last:border-b-0"
            >
              <p className="text-xs text-zinc-800">{reply.body}</p>
              <p className="mt-0.5 text-[11px] text-zinc-400">{reply.created_by}</p>
            </li>
          ))}
        </ul>
      )}

      {/* Reply form — only visible when the thread is active and not resolved */}
      {active && !thread.resolved && (
        <form
          onSubmit={handleReply}
          onClick={(e) => e.stopPropagation()}
          className="border-t border-zinc-100 px-3 py-2"
        >
          <textarea
            ref={replyInputRef}
            data-testid="annotation-reply-input"
            value={replyBody}
            onChange={(e) => setReplyBody(e.target.value)}
            placeholder="Reply…"
            rows={2}
            className="w-full text-xs border border-zinc-200 rounded px-2 py-1 resize-none focus:outline-none focus:ring-2 focus:ring-indigo-400"
          />
          {error && <p className="mt-1 text-[11px] text-red-600">{error}</p>}
          <div className="mt-1.5 flex items-center justify-between gap-2">
            <button
              type="submit"
              disabled={posting || !replyBody.trim()}
              data-testid="annotation-reply-submit"
              className="text-[11px] font-medium text-white bg-indigo-500 hover:bg-indigo-600 disabled:opacity-50 px-2.5 py-1 rounded"
            >
              {posting ? 'Posting…' : 'Reply'}
            </button>
            <button
              type="button"
              onClick={handleResolve}
              data-testid="annotation-resolve-button"
              className="text-[11px] text-zinc-500 hover:text-zinc-700"
            >
              Resolve
            </button>
          </div>
        </form>
      )}

      {/* Re-open button when resolved and active */}
      {active && thread.resolved && (
        <div className="border-t border-zinc-100 px-3 py-2" onClick={(e) => e.stopPropagation()}>
          <button
            type="button"
            onClick={handleResolve}
            data-testid="annotation-reopen-button"
            className="text-[11px] text-zinc-500 hover:text-zinc-700"
          >
            Re-open
          </button>
        </div>
      )}
    </div>
  );
}

// ---------------------------------------------------------------------------
// NewThreadForm — popover for creating a thread from a text selection
// ---------------------------------------------------------------------------

export interface NewThreadAnchor {
  /** The selected text. */
  text: string;
  /** Character offset of selection start in the version content. */
  startOffset: number;
  /** Character offset of selection end in the version content. */
  endOffset: number;
  /** Client rect of the selection — for popover positioning. */
  rect: DOMRect;
}

export function NewThreadForm({
  anchor,
  customerId,
  versionId,
  onCreated,
  onCancel,
}: {
  anchor: NewThreadAnchor;
  customerId: string;
  versionId: string;
  onCreated: (thread: AnnotationThread) => void;
  onCancel: () => void;
}): React.ReactElement {
  const [body, setBody] = useState('');
  const [posting, setPosting] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const inputRef = useRef<HTMLTextAreaElement>(null);

  // Auto-focus when the form mounts.
  useEffect(() => {
    inputRef.current?.focus();
  }, []);

  const handleSubmit = useCallback(
    async (e: React.FormEvent) => {
      e.preventDefault();
      if (!body.trim()) return;
      setPosting(true);
      setError(null);
      try {
        const res = await fetch(
          `/api/wiki/pages/${encodeURIComponent(customerId)}/versions/${encodeURIComponent(versionId)}/annotations`,
          {
            method: 'POST',
            credentials: 'include',
            headers: { 'Content-Type': 'application/json' },
            body: JSON.stringify({
              anchor_text: anchor.text,
              start_offset: anchor.startOffset,
              end_offset: anchor.endOffset,
              body: body.trim(),
            }),
          },
        );
        if (!res.ok) {
          const respBody = await res.json().catch(() => ({}));
          throw new Error((respBody as { error?: string }).error ?? `HTTP ${res.status}`);
        }
        const thread = (await res.json()) as AnnotationThread;
        onCreated(thread);
      } catch (err) {
        setError(err instanceof Error ? err.message : 'Failed to create thread');
      } finally {
        setPosting(false);
      }
    },
    [body, anchor, customerId, versionId, onCreated],
  );

  return (
    <form data-testid="new-thread-form" onSubmit={handleSubmit} className="flex flex-col gap-2">
      <div className="text-[11px] text-zinc-500 italic border-l-2 border-indigo-300 pl-2 truncate">
        {anchor.text}
      </div>
      <textarea
        ref={inputRef}
        data-testid="new-thread-body-input"
        value={body}
        onChange={(e) => setBody(e.target.value)}
        placeholder="Add a comment…"
        rows={3}
        className="text-xs border border-zinc-200 rounded px-2 py-1 resize-none focus:outline-none focus:ring-2 focus:ring-indigo-400"
      />
      {error && <p className="text-[11px] text-red-600">{error}</p>}
      <div className="flex items-center gap-2">
        <button
          type="submit"
          disabled={posting || !body.trim()}
          data-testid="new-thread-submit"
          className="text-[11px] font-medium text-white bg-indigo-500 hover:bg-indigo-600 disabled:opacity-50 px-2.5 py-1 rounded"
        >
          {posting ? 'Saving…' : 'Comment'}
        </button>
        <button
          type="button"
          onClick={onCancel}
          data-testid="new-thread-cancel"
          className="text-[11px] text-zinc-500 hover:text-zinc-700"
        >
          Cancel
        </button>
      </div>
    </form>
  );
}

// ---------------------------------------------------------------------------
// AnnotationSidebar
// ---------------------------------------------------------------------------

export interface AnnotationSidebarProps {
  customerId: string;
  versionId: string;
  /** Content of the current wiki version — used for fuzzy re-anchoring. */
  content: string;
  /** When set, a new-thread form is shown for this selection. */
  pendingAnchor: NewThreadAnchor | null;
  onPendingAnchorCleared: () => void;
  /** Notify parent when threads update so highlight markers can refresh. */
  onThreadsChange?: (threads: AnnotationThread[]) => void;
}

/**
 * AnnotationSidebar — lists threads for the current wiki version and handles
 * new-thread creation via a popover form.
 *
 * No mocks — fetches real data from the annotation threads API.
 */
export function AnnotationSidebar({
  customerId,
  versionId,
  content,
  pendingAnchor,
  onPendingAnchorCleared,
  onThreadsChange,
}: AnnotationSidebarProps): React.ReactElement {
  const [threads, setThreads] = useState<AnnotationThread[]>([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);
  const [activeThreadId, setActiveThreadId] = useState<string | null>(null);

  // Fetch threads when versionId changes.
  useEffect(() => {
    let cancelled = false;
    setLoading(true);
    setError(null);

    fetch(
      `/api/wiki/pages/${encodeURIComponent(customerId)}/versions/${encodeURIComponent(versionId)}/annotations`,
      { credentials: 'include' },
    )
      .then(async (res) => {
        if (!res.ok) {
          const body = await res.json().catch(() => ({}));
          throw new Error((body as { error?: string }).error ?? `HTTP ${res.status}`);
        }
        return res.json() as Promise<{ threads: AnnotationThread[] }>;
      })
      .then((data) => {
        if (cancelled) return;
        setThreads(data.threads);
        onThreadsChange?.(data.threads);
      })
      .catch((err: unknown) => {
        if (cancelled) return;
        setError(err instanceof Error ? err.message : 'Unknown error');
      })
      .finally(() => {
        if (!cancelled) setLoading(false);
      });

    return () => {
      cancelled = true;
    };
  }, [customerId, versionId, onThreadsChange]);

  const handleThreadCreated = useCallback(
    (thread: AnnotationThread) => {
      const updated = [...threads, thread];
      setThreads(updated);
      onThreadsChange?.(updated);
      setActiveThreadId(thread.id);
      onPendingAnchorCleared();
    },
    [threads, onThreadsChange, onPendingAnchorCleared],
  );

  const handleResolved = useCallback(
    (threadId: string, resolved: boolean) => {
      const updated = threads.map((t) => (t.id === threadId ? { ...t, resolved } : t));
      setThreads(updated);
      onThreadsChange?.(updated);
    },
    [threads, onThreadsChange],
  );

  const handleReplyPosted = useCallback(
    (threadId: string, reply: AnnotationReply) => {
      const updated = threads.map((t) =>
        t.id === threadId ? { ...t, replies: [...t.replies, reply] } : t,
      );
      setThreads(updated);
      onThreadsChange?.(updated);
    },
    [threads, onThreadsChange],
  );

  // Compute re-anchored offsets for each thread so stale threads show a warning.
  const anchors = threads.map((t) => resolveAnchor(content, t));

  if (loading) {
    return (
      <div
        data-testid="annotation-sidebar"
        className="flex items-center justify-center h-16 text-zinc-400 text-xs"
      >
        Loading annotations…
      </div>
    );
  }

  if (error) {
    return (
      <div data-testid="annotation-sidebar" className="p-3 text-xs text-red-600">
        Failed to load annotations: {error}
      </div>
    );
  }

  const openThreads = threads.filter((t) => !t.resolved);
  const resolvedThreads = threads.filter((t) => t.resolved);

  return (
    <div data-testid="annotation-sidebar" className="flex flex-col gap-2 p-2">
      {/* New thread form */}
      {pendingAnchor && (
        <div className="rounded-lg border border-indigo-300 bg-indigo-50 p-3">
          <p className="text-[10px] font-semibold text-indigo-700 uppercase tracking-wide mb-2">
            New comment
          </p>
          <NewThreadForm
            anchor={pendingAnchor}
            customerId={customerId}
            versionId={versionId}
            onCreated={handleThreadCreated}
            onCancel={onPendingAnchorCleared}
          />
        </div>
      )}

      {/* Open threads */}
      {openThreads.length === 0 && !pendingAnchor && (
        <p className="text-xs text-zinc-400 text-center py-4">
          No annotations yet. Select text to add a comment.
        </p>
      )}

      {openThreads.map((thread) => (
        <div key={thread.id}>
          {anchors[threads.indexOf(thread)] === null && (
            <p className="text-[11px] text-amber-600 px-1 pb-1">
              Anchor unavailable — content changed.
            </p>
          )}
          <AnnotationThreadCard
            thread={thread}
            customerId={customerId}
            versionId={versionId}
            active={thread.id === activeThreadId}
            onClick={() => setActiveThreadId(thread.id === activeThreadId ? null : thread.id)}
            onResolved={handleResolved}
            onReplyPosted={handleReplyPosted}
          />
        </div>
      ))}

      {/* Resolved threads (collapsed section) */}
      {resolvedThreads.length > 0 && (
        <details className="mt-2">
          <summary className="text-[11px] text-zinc-400 cursor-pointer select-none">
            {resolvedThreads.length} resolved
          </summary>
          <div className="flex flex-col gap-2 mt-2">
            {resolvedThreads.map((thread) => (
              <AnnotationThreadCard
                key={thread.id}
                thread={thread}
                customerId={customerId}
                versionId={versionId}
                active={thread.id === activeThreadId}
                onClick={() => setActiveThreadId(thread.id === activeThreadId ? null : thread.id)}
                onResolved={handleResolved}
                onReplyPosted={handleReplyPosted}
              />
            ))}
          </div>
        </details>
      )}
    </div>
  );
}
