name: Full-Page User Story Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
      - name: Install Dependencies
        run: bun install
      - name: Install Playwright OS Dependencies
        run: bunx playwright install-deps && bunx playwright install chromium
      - name: Run E2E Tests
        run: bunx playwright test
        env:
          FIXTURES: "true"
